export const TOKENS = [
   'BTC',
   'WRX',
   'TKO',
   'BNB',
   'JOE',
   'AVAX',
   'UTK',
   'EGLD',
   'ONG',
   'ONT',
   'RAY',
   'SOL',
   'FIDA',
   'FTT',
   'WIF',
   'DIA',
   'UNFI',
   'DEGO',
   'JUP',
   'JTO',
   'ETH',
   'USTC',
   'LUNA',
   'KNC',
   'MASK',
   'FLUX',
   'CFX',
   'YGG',
   'APE',
   'TVK',
   'ERN',
   'PROM',
   'AR',
   'AGIX',
   'FET',
   'OCEAN',
   'NMR',
   'RNDR',
   'MDT',
   'GRT',
   'BAND',
   'API3',
   'TRB',
   'RLC',
   'LINK',
   'PYTH',
   'ACA',
   'PHA',
   'LIT',
   'KSM',
   'DOT',
   'STEEM',
   'SNT',
   'STMX',
   'HIVE',
   'MBL',
   'IRIS',
   'NKN',
   'LTO',
   'LOOM',
   'SC',
   'DATA',
   'STORJ',
   'STRAX',
   'ANKR',
   'BLZ',
   'FIL',
   'MANA',
   'SAND',
   'HIGH',
   'PYR',
   'GMT',
   'VTHO',
   'VET',
   'TFUEL',
   'THETA',
   'ALT',
   'DYM',
   'OP',
   'POL',
   'LDO',
   'XRP',
   'XLM',
   'HBAR',
   'ALGO',
   'QNT',
   'GTC',
   'CVP',
   'CVC',
   'AUCTION',
   'FARM',
   'CHESS',
   'ALPACA',
   'TWT',
   'C98',
   'SFP',
   'SXP',
   'ENA',
   'BAKE',
   'ROSE',
   'OSMO',
   'AXL',
   'KAVA',
   'SCRT',
   'ATOM',
   'ZEN',
   'ZEC',
   'WLD',
   'KEY',
   'COTI',
   'ADA',
   'CELO',
   'GAS',
   'FLM',
   'NEO',
   'DUSK',
   'STG',
   'ENS',
   'ID',
   'CKB',
   'VITE',
   'T',
   'KMD',
   'JASMY',
   'HNT',
   'DOCK',
   'GHST',
   'LOKA',
   'SLP',
   'AXS',
   'ATM',
   'LAZIO',
   'SANTOS',
   'ALPINE',
   'CHZ',
   'TROY',
   'POLYX',
   'MOVR',
   'GLMR',
   'ARB',
   'ETHFI',
];

export const tokenSuggestions = {
   WRX: ['TKO', 'BNB'],
   TKO: ['BNB', 'WRX'],
   BNB: ['WRX', 'TKO'],
   JOE: ['AVAX'],
   AVAX: ['JOE'],
   UTK: ['EGLD'],
   EGLD: ['UTK'],
   ONG: ['ONT'],
   MASK: ['FLUX', 'CFX', 'YGG', 'APE', 'TVK', 'ERN', 'PROM', 'AR'],
   FLUX: ['CFX', 'YGG', 'APE', 'TVK', 'ERN', 'PROM', 'AR'],
   CFX: ['YGG', 'APE', 'TVK', 'ERN', 'PROM', 'AR'],
   YGG: ['APE', 'TVK', 'ERN', 'PROM', 'AR'],
   APE: ['TVK', 'ERN', 'PROM', 'AR'],
   TVK: ['ERN', 'PROM', 'AR'],
   ERN: ['PROM', 'AR'],
   PROM: ['AR'],
   AGIX: ['FET', 'OCEAN', 'NMR', 'RNDR', 'ORAI', 'MDT', 'GRT'],
   FET: ['OCEAN', 'NMR', 'RNDR', 'ORAI', 'MDT', 'GRT'],
   OCEAN: ['NMR', 'RNDR', 'ORAI', 'MDT', 'GRT'],
   NMR: ['RNDR', 'ORAI', 'MDT', 'GRT'],
   RNDR: ['ORAI', 'MDT', 'GRT'],
   MDT: ['GRT'],
   BAND: ['API3', 'TRB', 'RLC', 'LINK', 'PYTH', 'DIA'],
   API3: ['TRB', 'RLC', 'LINK', 'PYTH', 'DIA'],
   TRB: ['RLC', 'LINK', 'PYTH', 'DIA'],
   RLC: ['LINK', 'PYTH', 'DIA'],
   LINK: ['PYTH', 'DIA'],
   PYTH: ['DIA'],
   ACA: ['PHA', 'LIT', 'KSM', 'DOT'],
   PHA: ['LIT', 'KSM', 'DOT'],
   LIT: ['KSM', 'DOT'],
   KSM: ['DOT'],
   STEEM: ['SNT', 'STMX', 'HIVE', 'MBL'],
   SNT: ['STMX', 'HIVE', 'MBL'],
   STMX: ['HIVE', 'MBL'],
   HIVE: ['MBL'],
   IRIS: ['NKN', 'LTO', 'LOOM'],
   NKN: ['LTO', 'LOOM'],
   LTO: ['LOOM'],
   SC: ['MDT', 'DATA', 'STORJ', 'STRAX', 'ANKR', 'AR', 'BLZ', 'FIL'],
   MDT: ['DATA', 'STORJ', 'STRAX', 'ANKR', 'AR', 'BLZ', 'FIL'],
   DATA: ['STORJ', 'STRAX', 'ANKR', 'AR', 'BLZ', 'FIL'],
   STORJ: ['STRAX', 'ANKR', 'AR', 'BLZ', 'FIL'],
   STRAX: ['ANKR', 'AR', 'BLZ', 'FIL'],
   ANKR: ['AR', 'BLZ', 'FIL'],
   AR: ['BLZ', 'FIL'],
   BLZ: ['FIL'],
   MANA: ['SAND', 'HIGH', 'PYR'],
   SAND: ['HIGH', 'PYR'],
   HIGH: ['PYR'],
   PYR: [],
   GMT: ['ACA', 'PHA', 'KSM', 'DOT'],
   ACA: ['PHA', 'KSM', 'DOT'],
   PHA: ['KSM', 'DOT'],
   KSM: ['DOT'],
   VTHO: ['FET'],
   TFUEL: ['THETA'],
   ALT: ['DYM', 'OP', 'POL', 'LDO', 'ETH'],
   DYM: ['OP', 'POL', 'LDO', 'ETH'],
   OP: ['POL', 'LDO', 'ETH'],
   POL: ['LDO', 'ETH'],
   LDO: ['ETH'],
   XRP: ['XLM', 'HBAR', 'ALGO', 'QNT'],
   XLM: ['HBAR', 'ALGO', 'QNT'],
   HBAR: ['ALGO', 'QNT'],
   ALGO: ['QNT'],
   GTC: ['CVP', 'CVC'],
   CVP: ['CVC'],
   AUCTION: ['DEGO', 'FARM', 'CHESS', 'ALPACA', 'UNFI', 'FOR'],
   DEGO: ['FARM', 'CHESS', 'ALPACA', 'UNFI', 'FOR'],
   FARM: ['CHESS', 'ALPACA', 'UNFI', 'FOR'],
   CHESS: ['ALPACA', 'UNFI', 'FOR'],
   ALPACA: ['UNFI', 'FOR'],
   UNFI: ['FOR'],
   TWT: ['C98', 'SFP', 'SXP', 'ENA'],
   C98: ['SFP', 'SXP', 'ENA'],
   SFP: ['SXP', 'ENA'],
   SXP: ['ENA'],
   TVK: ['BAKE', 'DEGO', 'ERN', 'NFT'],
   BAKE: ['DEGO', 'ERN', 'NFT'],
   DEGO: ['ERN', 'NFT'],
   ERN: ['NFT'],
   ROSE: ['OSMO', 'AXL', 'KAVAK', 'SCRT', 'ATOM'],
   OSMO: ['AXL', 'KAVAK', 'SCRT', 'ATOM'],
   AXL: ['KAVAK', 'SCRT', 'ATOM'],
   KAVAK: ['SCRT', 'ATOM'],
   SCRT: ['ATOM'],
   SCRT: ['ZEN', 'ZEC', 'WLD', 'KEY', 'CVC', 'SYS'],
   ZEN: ['ZEC', 'WLD', 'KEY', 'CVC', 'SYS'],
   ZEC: ['WLD', 'KEY', 'CVC', 'SYS'],
   WLD: ['KEY', 'CVC', 'SYS'],
   KEY: ['CVC', 'SYS'],
   CVC: ['SYS'],
   SOL: ['ETH', 'AVAX', 'SUI'],
   ETH: ['AVAX', 'SUI'],
   AVAX: ['SUI'],
   COTI: ['ADA', 'CELO'],
   ADA: ['CELO'],
   GAS: ['FLM', 'NEO'],
   FLM: ['NEO'],
   DUSK: ['STG'],
   ENS: ['ID'],
   DUSK: ['CKB', 'IRIS', 'VITE'],
   CKB: ['IRIS', 'VITE'],
   IRIS: ['VITE'],
   T: ['KMD', 'NKN'],
   KMD: ['NKN'],
   JASMY: ['HNT'],
   DOCK: ['ONT'],
   QNT: ['CVC', 'KEY'],
   CVC: ['KEY'],
   GHST: ['LOKA', 'SLP', 'AXS'],
   LOKA: ['SLP', 'AXS'],
   SLP: ['AXS'],
   OG: ['ATM', 'LAZION', 'SANTOS', 'ALPINE'],
   ATM: ['LAZION', 'SANTOS', 'ALPINE'],
   LAZION: ['SANTOS', 'ALPINE'],
   SANTOS: ['ALPINE'],
   TROY: ['POLXY', 'ONE'],
   POLXY: ['ONE'],
   MOVR: ['GLMR'],
   LDO: ['POL', 'ARB', 'OP', 'ETHFI', 'ETH'],
   POL: ['ARB', 'OP', 'ETHFI', 'ETH'],
   ARB: ['OP', 'ETHFI', 'ETH'],
   OP: ['ETHFI', 'ETH'],
   ETHFI: ['ETH'],
   BTC: [], // Tidak ada saran pembelian untuk Bitcoin
};
